import React from 'react';

const Terms = () => {
    return (
    <div className="text-left p-2">
        <b>Términos y Condiciones del servicio de Médico Online de UMA </b>
        <ul>
<li>
1. Definiciones: 
<br />- ENTIDAD -: Se entiende por ENTIDAD - a International Health Services Argentina S.A. (“IHSA”)- (En adelante “LA ENTIDAD”). 
<br />- ASOCIADO/S: Se entiende por asociado/s a la/s persona/s que se encuentra/n afiliada/s a los SERVICIOS médico asistenciales que brinda Doctor Online de UMA (En adelante “UMA”). 
<br />- USUARIO: Se entiende por USUARIO al asociado de UMA que se ha registrado en la progressive web app de UMA y utiliza el SERVICIO de video llamada para acceder a un médico en la especialidad de clínica médica (En adelante el “USUARIO”). 
<br />- SERVICIO: Se entiende por SERVICIO al sistema de acceso a un profesional médico exclusivamente en la especialidad de clínica médica mediante video llamada brindado por LA ENTIDAD y/o por terceros contratados por LA ENTIDAD al efecto, y que se encuentra disponible en la aplicación móvli de UMA denominada “UMA”.
<br /></li>
<br /><li>
<br />2. Generalidades: Las presentes condiciones generales (en adelante denominadas “Condiciones Generales”) regulan los términos y condiciones de acceso y uso del SERVICIO “UMA”, que pone a disposición LA ENTIDAD con el alcance y hasta los límites que se definen en estas Condiciones Generales, las cuales el USUARIO deberá leer, entender y aceptar para hacer uso del SERVICIO y obtener el asesoramiento que se brinda a través del mismo. El sólo acceso y/o utilización del SERVICIO, de todos o parte de sus contenidos, implica la plena aceptación de las presentes Condiciones Generales. 
<br />El SERVICIO que se brinda a través de “UMA” consiste en la posibilidad de que el USUARIO realice una consulta no presencial, de carácter virtual, a un profesional médico en la especialidad de Médico Clínico. La consulta tendrá una duración máxima de 15´ (quince minutos) y podrá ser realizada en días hábiles de lunes a viernes, en el horario de 9 a 19 hs., mediante una video llamada que se encuentra disponible en la progressive web app de UMA respetando las condiciones particulares y específicas que delimitan el alcance del mismo. En caso que el profesional elegido para realizar la consulta no se encontrare disponible, el USUARIO tendrá la opción de solicitar que el profesional pueda contactarlo por el mismo aplicativo UMA dentro de las 24 h hábiles subsiguientes. LA ENTIDAD podrá modificar las Condiciones Generales en cualquier momento, previa notificación a los USUARIOS. 
<br />3. Condiciones Particulares de uso del SERVICIO: 
<br />i. La consulta médica mediante este SERVICIO, no reemplaza ni sustituye la consulta médica presencial. 
<br />ii. La consulta médica mediante este SERVICIO, no reemplaza ni sustituye la consulta médica de guardia en instituciones medico asistenciales. 
<br />iii. El SERVICIO se encuentra disponible exclusivamente para los afiliados de Emergencias de todo el país en la medida en que se comuniquen desde un dispositivo móvil o pc con conexión a internet. 
<br />iv. Los profesionales que brindan el SERVICIO lo hacen exclusivamente en la especialidad de Cínica Médica. 
<br />v. En caso de ser necesario y a criterio del profesional consultado, el USUARIO podrá ser derivado a un médico especialista, o bien podrá ser derivado para la realización de estudios de diagnóstico o tratamiento. 
<br />vi. En caso de urgencia y/o emergencia, el USUARIO deberá dirigirse la guardia de institución de cartilla conforme su plan Emergencias o comunicarse telefónicamente con el SERVICIO de Emergencias llamando al  0800-888-3637. 
<br />vii. El SERVICIO se encuentra disponible para asociados de UMA que hayan cumplido con la registración en la página web o App de UMA mediante “email de USUARIO” y “contraseña”. 
<br />viii. La cantidad de consultas médicas que podrá realizar el USUARIO se encuentra limitada conforme lo establezca el plan médico contratado, o conforme se indique a través de la página web de UMA, no pudiendo exceder 10 consultas anuales por afiliado por este sistema. Una vez agotada la cantidad de consultas disponibles y en caso que LA ENTIDAD le habilite nuevas consultas, el USUARIO deberá aceptar nuevamente las presentes Condiciones Generales para volver a hacer uso del SERVICIO. 
<br />ix. El SERVICIO únicamente se encuentra disponible para ser utilizado a través de la página web o la App de UMA mediante el sistema de video llamada, no estando autorizado ni disponible a través de otro sistema diferente. 
<br />x. El SERVICIO es sin cargo para el USUARIO hasta una determinada cantidad de consultas. Una vez agotadas las mismas, las consultas siguientes estarán - sujetas a un copago el cual variará según el plan médico de Emergencias contratado por el USUARIO. 
<br />xi. LA ENTIDAD se reserva el derecho de finalizar el SERVICIO previa notificación a los USUARIOS. 
<br />xii. El SERVICIO no incluye las especialidades o SERVICIOS detallados en el apartado 6 de las presentes Condiciones Generales. 
<br />xiii. El SERVICIO no podrá ser utilizado por ASOCIADOS que se encuentren en mora en el pago de su factura de UMA. 
<br />xiv. El SERVICIO se encuentra sujeto a disponibilidad técnica del acceso a internet o SERVICIO de conectividad que posea el USUARIO. Para una correcta y eficaz utilización del SERVICIO, se sugiere, como mínimo, con los siguientes SERVICIOs: Requisitos Mínimos: 
<br />Navegador Google Chrome (Última Versión). 
<br />Sistema operativo: Windows 10 32 bit, Windows 8.1 32 Bit, Windows 8 32 Bit, Windows 7 32 Bit, Procesador: Intel Celeron dual Core / Intel Core 2 Dual-Core @ 2.40GHz / AMD Athlon @ 2.5GHz, Memoria RAM: 2GB, Velocidad Internet: 5Mb de bajada / 1mb de subida o superior, Micrófono y Cámara web (640x480) 
<br />Requisitos recomendados: Sistema operativo: Windows 10 64 Bit, Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit, Procesador: Intel Core i3 3.2GHZ / AMD Phenom II @ 3.30GHZ, Memoria RAM: 4GB, Velocidad Internet: 10Mb de bajada / 2Mb de subida, Micrófono y Cámara web (1280x720). 
<br />4. Obligaciones del USUARIO. El USUARIO deberá respetar en todo momento los términos y condiciones establecidos en las presentes Condiciones Generales. De forma expresa, el USUARIO manifiesta que utilizará el SERVICIO de forma responsable, diligente y asumiendo cualquier responsabilidad que pudiera derivarse del incumplimiento de las presentes Condiciones Generales. El USUARIO reconoce y declara aceptar que efectuará consultas a través del SERVICIO exclusivamente referidas a su propia salud y no respecto de terceros; Su incumplimiento facultará a la ENTIDAD a resolver el presente contrato por culpa del USUARIO y a accionar civil y penalmente por los daños y perjuicios ocasionados. 
<br />5. Responsabilidad de LA ENTIDAD. Límites. LA ENTIDAD no ofrece garantía de resultado alguno en relación al consejo médico, indicación o diagnóstico que le brinde el profesional consultado al USUARIO a través del SERVICIO. 
<br />El USUARIO reconoce y acepta que ni LA ENTIDAD ni el profesional consultado otorgan ninguna garantía de cualquier naturaleza, ya sea expresa o implícita, sobre la información, consejo médico, asesoramiento, contenidos, información y SERVICIOS que ofrece LA ENTIDAD a través del SERVICIO toda vez que no asume una obligación de resultado. 
<br />LA ENTIDAD no será responsable por agravamientos de los eventuales cuadros clínicos, en caso que el USUARIO no pudiera realizar posteriormente un efectivo contacto con el médico consultado o con el especialista al cual fue derivado, o no se realizare los estudios sugeridos por el profesional. Exceptuando los casos que la legislación vigente de la República Argentina imponga expresamente lo contrario, y exclusivamente con la medida y extensión en que lo imponga, LA ENTIDAD no garantiza ni asume responsabilidad alguna respecto a los posibles daños y perjuicios causados por el uso del SERVICIO. 
<br />6. Exclusiones: Se deja expresamente establecido y así lo acepta el USUARIO que quedan excluidas del SERVICIO cualquier especialidad médica que no resulte clínica médica Asimismo, se establece que se encuentran expresamente excluidas las siguientes especialidades y/o prestaciones: - SALUD MENTAL - URGENCIAS O EMERGENCIAS - RECETAS para MEDICACION CRONICA - CERTIFICADOS MEDICOS - APTOS FISICOS - Cualquier otra que por su naturaleza y/o complejidad no pueda brindarse a través del SERVICIO. 
<br />7. Propiedad intelectual e industrial Todos los contenidos, marcas, dominios, logos, dibujos, documentación, programas informáticos o cualquier otro elemento susceptible de protección por la legislación de propiedad intelectual o industrial, que sean accesibles en la web corresponden exclusivamente a LA ENTIDAD o a sus legítimos titulares y quedan expresamente reservados todos los derechos sobre los mismos, o bien LA ENTIDAD posee las licencias necesarias para su uso. Queda expresamente prohibida la creación de enlaces de hipertexto (links) a cualquier elemento integrante de la página web sin la previa autorización en forma expresa por parte de LA ENTIDAD. 
<br />8. Confidencialidad. Se deja expresa constancia que las consultas que el USUARIO realice a través del SERVICIO, en ningún caso y bajo ninguna circunstancia serán sometidas a grabación, ni de voz ni de imagen por parte de la ENTIDAD, con el fin de garantizar la confidencialidad de la información que se vierta en el mismo, y de resguardar y preservar el secreto médico, conforme lo exigen las normas que rigen la materia (cf. Ley Nro. 25.326 de Protección de los Datos Personales, Ley 26.529 de Derechos del Paciente en su Relación con los Profesionales e Instituciones de la Salud y sus modificaciones y reglamentación aplicable). En forma concordante, el USUARIO reconoce y declara aceptar que bajo ninguna circunstancia someterá la consulta que realiza a grabación, ni de voz ni de imagen, tanto de su parte como del profesional médico interviniente. Su incumplimiento facultará a la ENTIDAD a resolver el presente contrato por culpa del USUARIO y a accionar civil y penalmente por los daños y perjuicios ocasionados. 
<br />9. Legislación aplicable, jurisdicción competente y notificaciones Las presentes Condiciones Generales se rigen y se interpretan de acuerdo con las Leyes de la República Argentina. Para cualquier reclamo relacionado con el SERVICIO serán competentes los Tribunales Ordinarios de la Capital Federal. Todas las notificaciones, requerimientos, peticiones y otras comunicaciones que el USUARIO desee efectuar a LA ENTIDAD deberán realizarse por escrito y se entenderá que han sido correctamente realizadas cuando hayan sido recibidas en la siguiente dirección: Av. Av. Melián 2752, CABA.
<br /></li>
        </ul>
    </div>
    )
}

export default Terms