
var MedicalExamMotivoDeConsulta = [
	"Alteración aguda de la visión",
	"Alteración de la conducta",
	"Arritmia",
	"Atragantamiento",
	"Calambres",
	"Cianosis",
	"Complicaciones de herida quirúrgica",
	"Constipación",
	"Control de signos vitales",
	"Convulsiones",
	"Cuerpo extraño en orificio natural",
	"Curación",
	"Desmayo",
	"Diagnóstico de...(solicitante médico)",
	"Diarrea",
	"Dificultad para hablar",
	"Dificultad respiratoria",
	"Dolor abdominal",
	"Dolor anal",
	"Dolor cervical",
	"Dolor de boca",
	"Dolor de cabeza",
	"Dolor de extremidad",
	"Dolor de garganta",
	"Dolor de pecho",
	"Dolor en el pecho",
	"Dolor lumbar",
	"Dolor testicular",
	"Dolor toracico",
	"Embarazo con problemas",
	"Epistaxis",
	"Escalofrios",
	"Fiebre",
	"Hemorragia anal",
	"Hemorragia genital",
	"Hemorragia por boca",
	"Hinchazón o edema",
	"Hipertensión arterial",
	"Hipotensión arterial",
	"Ictericia",
	"Ingestion de...",
	"Llanto inconsolable (solo en menores de 3 años)",
	"Malestar general",
	"Mareos",
	"Mordedura",
	"Náuseas",
	"Palidez",
	"Palpitaciones",
	"Paresia",
	"Parestesias",
	"Pérdida de Conciencia",
	"Perdida de control de esfinteres",
	"Picadura",
	"Problema ocular",
	"Problema urinario o genital",
	"Problemas del oido",
	"Quemadura",
	"Reacción cutánea",
	"Sd gripal",
	"Solicitud de precario",
	"Sudoración",
	"Temblor",
	"Tos o expectoración",
	"Trauma de abdomen",
	"Trauma de cara",
	"Trauma de craneo",
	"Trauma de cuello",
	"Trauma de miembro inferior",
	"Trauma de miembro superior",
	"Trauma de pelvis",
	"Trauma de torax",
	"Trauma dorso lumbar",
	"Victima de abuso sexual",
	"Victima de accidente vehicular",
	"Victima de agresión o riña",
	"Victima de ahorcamiento",
	"Victima de caída de altura",
	"Victima de derrumbe o aplastamiento",
	"Victima de electrocución",
	"Victima de explosión",
	"Victima de gases tóxicos",
	"Victima de herida de arma blanca",
	"Victima de herida de arma de fuego",
	"Victima de incendio",
	"Vómitos"
]

export default MedicalExamMotivoDeConsulta;
