
var PatientTreatmentDiagnostic = [
	"Atención de enfermería",
	"CARV Accidente cerebrovasclar/ictus/apoplejía 301",
	"CARV Arritmia cardíaca NE 304",
	"CARV Choque, no clasificado en otra parte 307",
	"CARV Dolor cardíaco/atribuido corazón 320",
	"CARV Elevación de la presión arterial 329",
	"CARV Flebitis y tromboflebitis 339",
	"CARV Hipotensión sin especificar 345",
	"CARV Infarto agudo de miocardio 347",
	"CARV Insuficiencia cardíaca 349",
	"CARV Isquemia cardíaca con angina 351",
	"CARV Isquemia cardíaca sin angina 352",
	"CARV Otros signos/síntomas cardiovasculares 466",
	"CARV Parada cardiorrespiratoria 481",
	"DERM Otros signos/síntomas de la piel y faneras 467",
	"DERM Salpullido y otras erupciones cutáneas no especificadas 487",
	"DERM Tumefacción, masa o prominencia de la piel y del tejido subcutáneo localizadas 504",
	"DIGES Abdomen agudo 300",
	"DIGES Cuerpo extraño en tracto digestivo 311",
	"DIGES Diarrea 317",
	"DIGES Dispepsia/indigestión 318",
	"DIGES Dolor abdominal generalizado/retortijones 319",
	"DIGES Dolor de estómago/epigástrico 321",
	"DIGES Estreñimiento 334",
	"DIGES Hematemesis/vómito de sangre 341",
	"DIGES Ictericia 346",
	"DIGES Melena 356",
	"DIGES Otros dolores abdominales localizados 469",
	"DIGES Otros signos/síntomas del aparato digestivo 468",
	"DIGES Rectorragia/hemorragia rectal 484",
	"DIGES Signos/síntomas de boca, lengua y labios 491",
	"DIGES Signos/síntomas de dientes y encías 493",
	"DIGES Vómito 506",
	"EMBAR Hemorragia antes del parto 343",
	"EMBAR Otros problemas/enfermedades del embarazo/parto 470",
	"EMBAR Signos/síntomas de la mama/lactancia 496",
	"EMBAR Vómito/náusea del embarazo 507",
	"GENIT Dolor genital femenino 324",
	"GENIT Orquitis/epididimitis 461",
	"GENIT Otros signos/síntomas del aparato genital del hombre 471",
	"GENIT Otros signos/síntomas genital/mamas, mujer 472",
	"GENIT Sangrado intermenstrual 488",
	"GENIT Sangrado posmenopáusico 489",
	"HEMAT Adenopatía/dolor en ganglio linfático 302",
	"HEMAT Púrpura/alteraciones de la coagulación 483",
	"HEMAT Signos/síntomas de la sangre/órganos hematopoyéticos 497",
	"INESP Alergia/reacciones alérgicas NE 303",
	"INESP Desmayo/síncope 316",
	"INESP Dolor generalizado/múltiple 323",
	"INESP Dolor torácico NE 325",
	"INESP Edema, no clasificado en otra parte 326",
	"INESP Escalofríos 332",
	"INESP Fiebre 338",
	"INESP Otras enfermedades infecciosas NE 462",
	"INESP Otras enfermedades virales con exantema 465",
	"INESP Otros problemas sociales 479",
	"INESP Somnolencia, estupor y coma 501",
	"LOCOM Esguinces y distensiones NE 333",
	"LOCOM Otros signos/síntomas del aparato locomotor 473",
	"LOCOM Signos/síntomas articulares NE 490",
	"LOCOM Signos/síntomas de la espalda 494",
	"LOCOM Signos/síntomas del cuello 492",
	"LOCOM Signos/síntomas lumbares 495",
	"METAB Deshidratación 315",
	"METAB Hipoglucemia 344",
	"METAB Otros problemas endocrinos/metabólicos/nutricionales 474",
	"METAB Pérdida de peso 482",
	"NEURO Cefalea 306",
	"NEURO Convulsiones/crisis convulsivas 310",
	"NEURO Mareo y desvanecimiento 354",
	"NEURO Meningitis/encefalitis 357",
	"NEURO Movimientos involuntarios anormales 358",
	"NEURO Otros signos/síntomas neurológicos 475",
	"NEURO Vértigo/vahído 505",
	"OBITO Fallecimiento/muerte 336",
	"OFTAL Ojo rojo 460",
	"OFTAL Otras enfermedades/problemas de salud de ojos/anejos 463",
	"OTOL Cuerpo extraño en el oído 312",
	"OTOL Dolor de oído/oreja 322",
	"OTOL Otros signos/síntomas del oído/oreja 476",
	"OTOL Síndromes vertiginosos 498",
	"OTRO Derivado por otro 314",
	"OTRO Eval/Examen médico parcial/Pre-op. 335",
	"OTRO Medicación/prescripción/renovación/inyección355",
	"Precario médico",
	"PSICO Otros signos/síntomas psicológicos/mentales 477",
	"PSICO Síntomas y signos que involucran el estado emocional 500",
	"PSICO Síntomas y signos que involucran la apariencia y el comportamiento 499",
	"RESP Bronquitis/bronquiolitis aguda 305",
	"RESP Cuerpo extraño nariz/laringe/bronquios 313",
	"RESP Enfermedad pulmonar obstructiva crónica EPOC 330",
	"RESP Epistaxis/hemorragia nasal 331",
	"RESP Fatiga respiratoria/disnea 337",
	"RESP Gripe 340",
	"RESP Infección respiratoria aguda del tracto superior 348",
	"RESP Laringitis/traqueítis aguda 353",
	"RESP Neumonía 359",
	"RESP Otros signos/síntomas del aparato respiratorio 478",
	"RESP Respiración jadeante/sibilante 485",
	"TOXIC Complicación de tratamiento médico 309",
	"TOXIC Efectos tóxicos de sustancias no medicamentosas 328",
	"TOXIC Intoxicaciones/envenenamientos/sobredosificación por medicamentos 350",
	"TRAUM Efectos adversos factores físicos 327",
	"TRAUM Traumatismo/lesión NE 502",
	"TRAUM Traumatismos/lesiones múltiples 503",
	"UROL Cistitis/otras infecciones urinarias 308",
	"UROL Hematuria 342",
	"UROL Otros signos/síntomas del aparato urinario 480",
	"UROL Retención urinaria 486"
]

export default PatientTreatmentDiagnostic;
